name: Update repos

on:
  schedule:
    - cron: "0 0 * * 1" # Monday
    - cron: "0 0 * * 3" # Wednesday
    - cron: "0 0 * * 5" # Friday
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # See docs/CUSTOMIZE.md for details on how to set up PAT for triggering subsequent workflows
      #        with:
      #          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip" # caching pip dependencies
      - name: HELLP HELP MEEE 🍆
        run: |
          pip3 install --upgrade requests pyyaml
          python3 python_scripts/repos.py

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          echo "🔧 Git configured."

      - name: Commit and push if changed
        run: |
          git add _pages/repos.md
          git diff --staged --quiet || (
            echo "📤 Committing and pushing changes..."
            git commit -m "Update repos"
            git push
          )
